version: '3.7'
services:

  app:
    build: ./app
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - database

  database:
    image: postgres:latest 
    env_file:
      - postgres.env 
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data/ 
volumes:
  database-data:
